exclude_patterns:
- config/
- db/
- dist/
- features/
- **/node_modules/
- script/
- **/spec/
- **/test/
- **/tests/
- Tests/
- **/vendor/
- **/*_test.go
- **/*.d.ts
- **/*.js
- **/*test.ts
- **/*comp.ts