language: node_js

sudo: required

node_js:
  - "node"
  - "9"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - guilherme.moraes@outlook.com
    on_success: never
    on_failure: always

services:
  - rabbitmq

before_install:
  - npm install
  - set-integration-tests-environment.sh
  - rabbitmqadmin declare exchange name=enqueuer.exchange type=topic

script:
  - npm run lint
  - npm run build
  - npm run unitTest
  - npm link
  - npm run componentTest
#  - npm run integrationTest
