os: osx
language: node_js

node_js:
  - "node"
  - "9"

cache:
  directories:
    - node_modules

before_install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run unitTest
  - npm link
  - npm run componentTest
#  - npm run integrationTest
