language: node_js

sudo: required

node_js:
  - "9.11.1"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - guilherme.moraes@outlook.com
    on_success: never
    on_failure: always

services:
  - rabbitmq

before_install:
  - npm install
  - mkdir temp
  - wget -O temp/kafka_2.11-1.0.0.tgz https://archive.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz
  - cd temp
  - tar -xvzf kafka_2.11-1.0.0.tgz
  - cd kafka_2.11-1.0.0
  - bin/zookeeper-server-start.sh config/zookeeper.properties &
  - bin/kafka-server-start.sh ../../scripts/server.properties &
  - cd ../../
  - wget -O temp/elasticmq-server-0.13.11.jar https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.13.11.jar
  - java -Dconfig.file=scripts/elasticMq.conf -jar temp/elasticmq-server-0.13.11.jar &
  - ./scripts/rabbitmqadmin declare exchange name=enqueuer.exchange type=topic
  - temp/kafka_2.11-1.0.0/bin/kafka-topics.sh --create --topic enqueuer-topic-name --zookeeper localhost:2181 --partitions 3 --replication-factor 1 #We have to give some time for broker and zookeeper
  - sudo rabbitmq-plugins enable rabbitmq_mqtt
  - sudo rabbitmq-plugins enable rabbitmq_stomp

script:
  - npm run lint
  - npm run build
  - npm link
  - npm run inceptionTest
  - npm run codeCoverage
  - npm run integrationTest