language: node_js

sudo: required

node_js:
- v10.8.0

cache:
    directories:
    - node_modules

notifications:
    email:
        recipients:
        - guilherme.moraes@outlook.com
        on_success: never
        on_failure: always

before_install:
- npm install
- npm install codecov -g

script:
- rm output/*
- npm install
- npm run lint
- npm run build
- npm link
- npm run codeCoverage
- npm run examplesTest
- npm run listsDescriptions

after_success:
- codecov
