language: node_js

sudo: required

node_js:
  - "node"
  - "9"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - guilherme.moraes@outlook.com
    on_success: never
    on_failure: always

services:
  - rabbitmq

before_install:
  - npm install
  - mkdir temp
  - wget -O temp/elasticmq-server-0.13.11.jar https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.13.11.jar
  - java -Dconfig.file=scripts/elasticMq.conf -jar temp/elasticmq-server-0.13.11.jar &
  - ./scripts/rabbitmqadmin declare exchange name=enqueuer.exchange type=topic

script:
  - npm run lint
  - npm run build
  - npm run unitTest
  - npm link
  - npm run componentTest
  - npm run integrationTest
  - npm run codeCoverage
